WIDTH = 800
HEIGHT = WIDTH
CELL = WIDTH//8
FILES = [chr(i) for i in range(ord('a'), ord('i'))]
RANKS = [i for i in range(1,9)]
FPS = 60
PADDING = 5
BORDER = 2

BASIC_PIECE = 20
ADVANCED = 15
QUEEN_WEIGHT = 15
ATTACK_WEIGHT = 20
CAN_BE_CAPTURED = -20
CORNER = -5
WALL = -5