WIDTH = 800
HEIGHT = WIDTH
CELL = WIDTH//8
FILES = [chr(i) for i in range(ord('a'), ord('i'))]
RANKS = [i for i in range(1,9)]
FPS = 60
PADDING = 5
BORDER = 2

BASIC_PIECE = 20
ADVANCED = 15
QUEEN_WEIGHT = 5
ATTACK_WEIGHT = 15
CAN_BE_CAPTURED = -15
CORNER = -1
WALL = -0.5