WIDTH = 800
HEIGHT = WIDTH
CELL = WIDTH//8
FILES = [chr(i) for i in range(ord('a'), ord('i'))]
RANKS = [i for i in range(1,9)]
FPS = 60
PADDING = 5
BORDER = 2

PIECE = 10
ADVANCED = 3
QUEEN = 20
ATTACK_WEIGHT = 15
CAN_BE_CAPTURED = -25
CENTER = 3
AVAILABLE_MOVES = 2
CORNER = -5
WALL = 1